//Localizar arquivo CPM.js e alterar as seguintes linhas

quizReportingData: {
            ISRUnknownErrorStr: 'Resultados enviado com sucesso, um de nossos analistas irá recebe-lo!',
            ISRNoConnectionErrorStr: 'Sem conexão',
            ISRWrongURLErrorStr: 'URL incorreto',
            ISRLoginErrorStr: 'Login ou senha incorreto(a)',
            ISRConnectingStr: 'Conectando',
            ISRResultPostedStr: 'Resultados postados com êxito, um de nossos analistas irá recebe-lo!',
            ISRPostResultStr: 'Postar resultados',
            ISRResultCalculatedStr: 'Seus resultados para este quiz foram calculados e estão prontos para serem enviados para nossos analistas. Informe seu Nome e empresa, separando por um traço e clique em enviar.',
            ISREnterNameStr: 'Insira seu nome e empresa:',
            ISREmailIDStr: 'Insira seu e-mail:',
            ISRSendStr: 'Enviar >>',
            ISRStatusStr: 'Mensagem de status',
            ISRErrorStr: 'Mensagem de status de erro',
            ISROkStr: 'OK',
            lWriteDebugInfo: false,
            lmsType: 9,
            sendScoreAsPercent: true,
            trackingLevel: 0,
            slideViewPercentage: 100,
            reportingOption: 1,
            slideViewsForSuccess: 0,
            slideViewsTypeForSuccess: 0,
            slideViewsForCompletion: 0,
            slideViewsTypeForCompletion: 0,
            quizCriteriaForCompletion: 0,
            quizCriteriaForSuccess: 0,
            completionCriteria: 1,
            successCriteria: 1,
            internalServerURL: 'http://200.195.131.180//captivate/internalServerReporting.php',
            companyName: 'Inside Sistemas',
            departmentName: 'Suporte',
            courseName: 'Cadastro de Produtos',
            courseNode: '',
            isTrackedFlag: true,
            trackingUrlEncodeVersionAndSession: 1,
            commitDataOnEverySlide: true,
            trackingSendResumeData: true,
            cmiExitNormalAfterCompletion: false,
            lmsInitializationString: 'cp.movie.playbackController.SetLMSType();cp.movie.playbackController.SetSendScoreAsPercent();cp.movie.playbackController.SetTrackingLevel();cp.movie.playbackController.SetSlideViewPercentage();cp.movie.playbackController.SetReportingOption();cp.movie.playbackController.SetSlideViewsForSuccess();cp.movie.playbackController.SetSlideViewsForCompletion();cp.movie.playbackController.SetQuizCriteriaForCompletion();cp.movie.playbackController.SetQuizCriteriaForSuccess();cp.movie.playbackController.SetCompletionCriteria();cp.movie.playbackController.SetSuccessCriteria();cp.movie.playbackController.SetInternalServerURL();cp.movie.playbackController.SetDirectory();cp.movie.playbackController.SetCourseNode();cp.movie.playbackController.SetIsTrackedFlag();cp.movie.playbackController.SetTrackingUrlEncodeVersionAndSession();cp.movie.playbackController.SetCommitDataOnEverySlide();cp.movie.playbackController.SetTrackingSendResumeData();cp.movie.playbackController.SetCmiExitNormalAfterCompletion();'
        },
